views/js/controller/home/custom-scrollbar.js
preliminary work to make all TAO js code scoped, not using globals but only AMD dependencies
=> amdify the custom-scrollbar plugin

actions/structures.xml, manifest.php, model/entryPoint/TaoCeEntrypoint.php, scripts/install/overrideEntryPoint.php, scripts/update/Updater.php
requires https://github.com/oat-sa/tao-core/pull/434
=> Adapted to entrypoint registry

scripts/install/overrideEntryPoint.php
Requires https://github.com/oat-sa/tao-core/pull/551
=> Explicitly override entrypoint

model/entryPoint/TaoCeEntrypoint.php
depends on https://github.com/oat-sa/extension-tao-backoffice/pull/21
=> Adapted to entryPoint move

manifest.php, scripts/install/overrideEntryPoint.php, scripts/update/Updater.php
Related to: https://oat-sa.atlassian.net/browse/TAO-3067
Activate the guest access on the login page
=> Add guest access to the login page

actions/Main.php
related to https://github.com/oat-sa/tao-core/pull/1054
=> use configurable login page

composer.json, manifest.php, scripts/update/Updater.php
=> Release 3.8.3

composer.json, manifest.php, scripts/update/Updater.php
Required by https://github.com/oat-sa/extension-tao-delivery-rdf/pull/158
=> version and dependencies bump

composer.json, manifest.php, scripts/update/Updater.php
=> Release 3.14.0

composer.json, manifest.php, scripts/update/Updater.php
=> Release 3.18.0

manifest.php, scripts/update/Updater.php
Related to: https://oat-sa.atlassian.net/browse/TAO-5701
Simply require the extension `taoQtiTestPreviewer` in order to install the new item previewer.
=> Require taoQtiTestPreviewer

composer.json
=> Release 3.20.2

manifest.php, scripts/update/Updater.php
=> Release 3.21.0

composer.json, manifest.php, scripts/update/Updater.php
=> Release 4.1.0

composer.json, manifest.php, scripts/update/Updater.php
Update `taoDeliveryRdf` to `7.3.0`
=> bump version

actions/Main.php, manifest.php, scripts/update/Updater.php
=> Release 5.1.1

manifest.php, model/routing/EntryRoute.php, scripts/update/Updater.php
https://oat-sa.atlassian.net/browse/TAO-7391
=> Api changes related to new user API

composer.json, manifest.php, scripts/update/Updater.php
=> Release 5.5.0

composer.json, manifest.php, scripts/update/Updater.php
=> Release 5.6.0

composer.json, manifest.php, scripts/update/Updater.php
=> Release 6.0.0

composer.json, manifest.php, scripts/update/Updater.php
Update the dependency to taoDeliveryRdf version `8.2.1`
=> update dependency to taoDeliveryRdf

composer.json, manifest.php, scripts/update/Updater.php
=> Release 6.3.1

composer.json, manifest.php, scripts/update/Updater.php
=> Release 6.4.1

composer.json, manifest.php, scripts/update/Updater.php
=> update tao delivery rdf version

actions/Home.php, actions/Main.php, includes/raw_start.php, manifest.php, model/entryPoint/TaoCeEntrypoint.php, model/routing/EntryRoute.php, scripts/install/overrideEntryPoint.php, scripts/install/setDefaultResultServer.php, scripts/update/Updater.php
Hello, this PR is used to demonstrate phpcs fixer apply on taoCe extension. As a prototype, it does not contains version bump. It is using the same phpcs command as `http://qa.kitchen.it.taocloud.org/job/deploy-test-package/job/product-ci%252Ftaoce/lastStableBuild/php-code-sniffer/`
=> Fix code styling

actions/Home.php, actions/Main.php, includes/raw_start.php, manifest.php, model/entryPoint/TaoCeEntrypoint.php, model/routing/EntryRoute.php, scripts/install/overrideEntryPoint.php, scripts/install/setDefaultResultServer.php, scripts/update/Updater.php
=> Release 7.1.1

composer.json, manifest.php, scripts/update/Updater.php
=> Release 7.2.0

composer.json, manifest.php, scripts/update/Updater.php
Update tao delivery rdf requirement
=> Release 8.0.0

composer.json, manifest.php, scripts/update/Updater.php
=> Release 8.1.1

composer.json, manifest.php, scripts/update/Updater.php
=> Release 8.3.1

.Jenkinsfile, composer.json, manifest.php, scripts/update/Updater.php
=> Release 8.4.1

composer.json, manifest.php, scripts/update/Updater.php
=> Release 9.0.0

composer.json, manifest.php
=> Release 9.1.0

composer.json, manifest.php
=> Release 9.2.0

composer.json, manifest.php
=> Release 9.3.0

composer.json
=> Release 10.0.2

composer.json
Updated delivery rdf dependency version for release.
=> chore: Updated delivery rdf dependency version.

composer.json
=> Release 10.0.3

composer.json
The dependency to `tao-delivery-rdf` needs to be updated as per https://github.com/oat-sa/github-tools/wiki/Sprint-release-procedure#taodeliveryrdf
=> feat: update dependency to tao-delivery-rdf

composer.json
=> Release 10.1.0

composer.json
Update the version of the taoDeliveryRdf dependency, as per https://github.com/oat-sa/github-tools/wiki/Sprint-release-procedure#taodeliveryrdf
=> fix: update dependency to taoDeliveryRdf

composer.json
=> Release 10.1.1

.github/workflows/continuous-integration.yaml, composer.json
https://oat-sa.atlassian.net/browse/ADF-1097
https://oat-sa.atlassian.net/browse/ADF-1087
https://oat-sa.atlassian.net/browse/ADF-1105
PHP 8 migration
=> chore: update generis tao-core

actions/Home.php, actions/Main.php, includes/raw_start.php, manifest.php, model/entryPoint/TaoCeEntrypoint.php, model/routing/EntryRoute.php, scripts/install/overrideEntryPoint.php, scripts/update/Updater.php
**Associated Jira issue:** [ADF-1440](https://oat-sa.atlassian.net/browse/ADF-1440)
Apply PSR-12 autofixer.
[ADF-1440]: https://oat-sa.atlassian.net/browse/ADF-1440?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> chore: apply PSR-12

migrations/Version202306151234563977_taoCe.php
=> fix: fix migration

migrations/Version202306151234563977_taoCe.php
=> Release 11.0.3

manifest.php, scripts/uninstall/RemoveSectionVisibilityFilterEntry.php, scripts/uninstall/RevertEntryPoint.php, scripts/uninstall/UnregisterLoginController.php
=> Release 11.0.4
